-- =====================================================================
-- One-time data script — TXT-01 (transaction types). NOT a Flyway migration.
--
-- Run ONCE per database, as the Postgres superuser (bypasses RLS), BEFORE starting a Ledger build
-- that includes V22__Transaction_Types_And_Direction.sql. V22 adds a NOT NULL direction column and
-- a five-type CHECK, so it fails while legacy PURCHASE/CREDIT rows exist.
--
-- Legacy rows are removed rather than converted: until V22 runs, the old CHECK only allows
-- PURCHASE/CREDIT, so they can't be rewritten in place. The data is regenerated by re-uploading.
-- Their statements are removed too (transactions cascade, V18) so the same files can be
-- re-uploaded without tripping the duplicate-statement check (V15).
--
--   psql -h localhost -U postgres -d fintracker \
--        -f services/fintracker-ledger/scripts/one-time/2026-10-08_TXT-01_remove_pre_txt_transactions.sql
-- =====================================================================
BEGIN;

DELETE FROM ledger.statements
WHERE statement_id IN (
    SELECT DISTINCT statement_id
    FROM ledger.transactions
    WHERE type IN ('PURCHASE', 'CREDIT') AND statement_id IS NOT NULL
);

-- Manual and bank-sync rows (no statement).
DELETE FROM ledger.transactions WHERE type IN ('PURCHASE', 'CREDIT');

COMMIT;
